AllCops:
    TargetRubyVersion: 2.3.4
    Exclude:
        - 'caddy/**/*'
        - 'client/**/*'
        - 'config/**/*'
        - 'db/**/*'
        - 'docker/**/*'
        - 'log/**/*'
        - 'public/**/*'
        - 'tmp/**/*'
        - 'var/**/*'
        - 'vendor/**/*'

Metrics/AbcSize:
    Enabled: false
Metrics/BlockLength:
    Enabled: false
Metrics/LineLength:
    Enabled: false
Metrics/MethodLength:
    Enabled: false

Style/CommentedKeyword:
    Enabled: false
Style/Documentation:
    Enabled: false
