version: '3'
services:
    app:
        container_name: testifi_app
        image: testifi_app
        command: bundle exec rails s -p 3000 -b '0.0.0.0'
        working_dir: /usr/src/app
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ${PROJECT_DIR}:/usr/src/app
        ports:
            - "3000:3000"
        links:
            - db
    db:
        container_name: testifi_db
        image: postgres:9.4
        ports:
            - "5432"
