FROM node
WORKDIR /usr/src/app
ADD client/ .
RUN npm install
RUN npm run build

FROM abiosoft/caddy
COPY --from=0 /usr/src/app/build /srv
ADD caddy/Caddyfile.DEV /etc/Caddyfile.DEV
ADD caddy/Caddyfile.PRODUCTION /etc/Caddyfile.PRODUCTION
