version: '3.3'
services:
    clientdev:
        container_name: client_dev
        image: node
        command: sh -c 'npm install; npm start'
        working_dir: /usr/src/app
        user: ${HOST_UID}
        volumes:
            - ${PROJECT_DIR}/client:/usr/src/app
        ports:
            - "3001:3001"
        environment:
            PORT: 3001
        links:
            - app
