FROM node
WORKDIR /usr/src/app
ADD client/ .
RUN npm install
RUN npm run build

FROM abiosoft/caddy
COPY --from=0 /usr/src/app/build /srv
ADD caddy/Caddyfile.development /etc/Caddyfile.development
ADD caddy/Caddyfile.production /etc/Caddyfile.production
