version: '3.3'
services:
    app:
        container_name: testifi_app
        image: testifi_app
        command: sh -c "./wait-for-it.sh db:5432 -- rails db:create; rails db:migrate; bundle exec rails s -p 3000 -b '0.0.0.0'"
        working_dir: /usr/src/app
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ${PROJECT_DIR}:/usr/src/app
        ports:
            - "3000"
        links:
            - db
            - redis
        depends_on:
            - db
            - redis
        stdin_open: true
        tty: true
    db:
        container_name: testifi_db
        image: postgres:9.4
        ports:
            - "5432"
    redis:
        container_name: testifi_redis
        image: redis
        ports:
            - "6379"
    worker:
        container_name: testifi_worker
        image: testifi_app
        command: sh -c "./wait-for-it.sh db:5432 -- bundle exec sidekiq"
        working_dir: /usr/src/app
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ${PROJECT_DIR}:/usr/src/app
    caddy:
        container_name: testifi_caddy
        image: testifi_caddy
        command: ["--conf", "/etc/Caddyfile.${RUNTIME_ENV}", "--log", "stdout"]
        ports:
            - "80:80"
            - "443:443"
            - "2015:2015"
        volumes:
            - caddy:/root/.caddy
        links:
            - app
volumes:
    caddy:
